/** 英语内置卡组，保留原有分组及组内词条顺序。 */
import type { Deck, Word } from './types';

/** 以原有分组与下标生成 ID，兼容已保存的掌握标记。 */
const en = (group: string, rows: [string, string, string, string][]): Word[] =>
  rows.map(([term, meaning, example, exampleZh], i) => ({
    id: `en-${group}-${i}`,
    term,
    meaning,
    example,
    exampleZh,
  }));

export const EN_DECKS: Deck[] = [
  {
    id: 'en-flow',
    lang: 'en',
    title: '开发流程',
    subtitle: 'English · Workflow',
    words: en('flow', [
      [
        'deployment',
        'n. 部署',
        'The deployment to production is scheduled for Friday.',
        '定于周五部署到生产环境。',
      ],
      [
        'release',
        'n./v. 发布',
        'This release fixes several critical bugs.',
        '这个版本修复了几个严重缺陷。',
      ],
      [
        'rollback',
        'n. 回滚',
        'We had to perform a rollback after the failed deployment.',
        '部署失败后我们不得不执行回滚。',
      ],
      [
        'hotfix',
        'n. 热修复',
        'A hotfix was pushed to resolve the urgent issue.',
        '推送了一个热修复来解决紧急问题。',
      ],
      [
        'milestone',
        'n. 里程碑',
        'We reached our first milestone ahead of schedule.',
        '我们提前完成了第一个里程碑。',
      ],
      [
        'backlog',
        'n. 待办列表',
        'That feature request is still in the backlog.',
        '那个功能需求还在待办列表里。',
      ],
      [
        'sprint',
        'n. 冲刺迭代',
        'We plan to finish this task in the next sprint.',
        '我们计划在下个迭代完成这个任务。',
      ],
    ]),
  },
  {
    id: 'en-code',
    lang: 'en',
    title: '代码与协作',
    subtitle: 'English · Code & Git',
    words: en('code', [
      [
        'refactor',
        'v. 重构',
        'We should refactor this function to improve readability.',
        '我们应该重构这个函数以提高可读性。',
      ],
      [
        'deprecated',
        'adj. 已废弃的',
        'This API is deprecated and will be removed soon.',
        '这个接口已废弃，很快会被移除。',
      ],
      [
        'legacy code',
        '遗留代码',
        'The system contains a lot of legacy code.',
        '这个系统里有大量遗留代码。',
      ],
      [
        'boilerplate',
        'n. 样板代码',
        'The framework reduces boilerplate significantly.',
        '这个框架大幅减少了样板代码。',
      ],
      [
        'syntax',
        'n. 语法',
        "There's a syntax error on line 42.",
        '第 42 行有一个语法错误。',
      ],
      [
        'compile',
        'v. 编译',
        'The code compiles without any warnings.',
        '代码编译没有任何警告。',
      ],
      [
        'runtime',
        'n. 运行时',
        'This error only occurs at runtime.',
        '这个错误只在运行时出现。',
      ],
      [
        'repository',
        'n. 代码仓库',
        'Clone the repository to your local machine.',
        '把仓库克隆到你的本地机器。',
      ],
      [
        'commit',
        'v./n. 提交',
        'Please commit your changes before leaving.',
        '离开前请提交你的更改。',
      ],
      [
        'merge',
        'v./n. 合并',
        'There is a merge conflict in this branch.',
        '这个分支有合并冲突。',
      ],
      [
        'pull request',
        '拉取请求',
        "I've opened a pull request for this fix.",
        '我为这个修复开了一个 PR。',
      ],
    ]),
  },
  {
    id: 'en-debug',
    lang: 'en',
    title: '调试排错',
    subtitle: 'English · Debugging',
    words: en('debug', [
      [
        'reproduce',
        'v. 复现',
        "I can't reproduce this bug on my machine.",
        '我在自己机器上复现不了这个 bug。',
      ],
      [
        'breakpoint',
        'n. 断点',
        'Set a breakpoint at the beginning of the function.',
        '在函数开头设一个断点。',
      ],
      [
        'stack trace',
        '堆栈跟踪',
        'The stack trace shows where the error occurred.',
        '堆栈跟踪显示了错误发生的位置。',
      ],
      [
        'memory leak',
        '内存泄漏',
        'The app crashes due to a memory leak.',
        '应用因为内存泄漏崩溃了。',
      ],
      [
        'race condition',
        '竞态条件',
        'This bug is caused by a race condition.',
        '这个 bug 是由竞态条件引起的。',
      ],
      [
        'edge case',
        '边界情况',
        'We need to handle this edge case carefully.',
        '我们需要仔细处理这个边界情况。',
      ],
      [
        'debug',
        'v. 调试',
        'I spent the whole afternoon debugging this issue.',
        '我花了整个下午调试这个问题。',
      ],
      [
        'log',
        'n./v. 日志',
        'Check the logs to find the root cause.',
        '查看日志找出根本原因。',
      ],
      [
        'root cause',
        '根本原因',
        'We identified the root cause of the outage.',
        '我们找到了故障的根本原因。',
      ],
    ]),
  },
  {
    id: 'en-arch',
    lang: 'en',
    title: '架构性能',
    subtitle: 'English · Architecture',
    words: en('arch', [
      [
        'scalability',
        'n. 可扩展性',
        'Scalability is a key concern for this system.',
        '可扩展性是这个系统的关键考量。',
      ],
      [
        'latency',
        'n. 延迟',
        'We reduced the latency by adding a cache layer.',
        '我们通过增加缓存层降低了延迟。',
      ],
      [
        'throughput',
        'n. 吞吐量',
        'The server can handle 10,000 requests per second.',
        '服务器每秒可处理一万个请求。',
      ],
      [
        'load balancer',
        '负载均衡器',
        'The load balancer distributes traffic across servers.',
        '负载均衡器把流量分发到各台服务器。',
      ],
      [
        'microservice',
        'n. 微服务',
        'We split the monolith into microservices.',
        '我们把单体应用拆成了微服务。',
      ],
      [
        'cache',
        'n./v. 缓存',
        'The response is cached for ten minutes.',
        '响应被缓存十分钟。',
      ],
      [
        'database schema',
        '数据库模式',
        'We need to update the database schema.',
        '我们需要更新数据库模式。',
      ],
      [
        'container',
        'n. 容器',
        'The application runs in a Docker container.',
        '应用运行在 Docker 容器里。',
      ],
      [
        'API endpoint',
        '接口端点',
        'This API endpoint returns user information.',
        '这个接口端点返回用户信息。',
      ],
      [
        'middleware',
        'n. 中间件',
        'Authentication is handled by middleware.',
        '认证由中间件处理。',
      ],
    ]),
  },
  {
    id: 'en-comm',
    lang: 'en',
    title: '职场沟通',
    subtitle: 'English · Workplace',
    words: en('comm', [
      [
        'blocker',
        'n. 阻塞项',
        'This dependency issue is a blocker for the release.',
        '这个依赖问题是发布的阻塞项。',
      ],
      [
        'code review',
        '代码审查',
        'Your code review comments were very helpful.',
        '你的代码审查意见很有帮助。',
      ],
      [
        'nitpick',
        'n. 小意见',
        'Sorry for the nitpick, but could you rename this variable?',
        '抱歉挑个小毛病，能把这个变量改个名吗？',
      ],
      [
        'scope creep',
        '需求蔓延',
        'We must avoid scope creep to meet the deadline.',
        '为了赶上截止日期必须避免需求蔓延。',
      ],
      [
        'stakeholder',
        'n. 干系人',
        'We need approval from all stakeholders.',
        '我们需要所有干系人的批准。',
      ],
      [
        'deadline',
        'n. 截止日期',
        'The deadline for this feature is next Monday.',
        '这个功能的截止日期是下周一。',
      ],
      [
        'estimate',
        'v./n. 估算',
        'Can you estimate how long this task will take?',
        '你能估算一下这个任务要多久吗？',
      ],
      [
        'follow up',
        '跟进',
        "I'll follow up on this issue tomorrow.",
        '我明天会跟进这个问题。',
      ],
    ]),
  },
  {
    id: 'en-interview',
    lang: 'en',
    title: '面试高频',
    subtitle: 'English · Interview',
    words: en('interview', [
      [
        'trade-off',
        'n. 权衡',
        "There's a trade-off between performance and readability.",
        '性能和可读性之间需要权衡。',
      ],
      [
        'bottleneck',
        'n. 瓶颈',
        'The database query is the main bottleneck.',
        '数据库查询是主要瓶颈。',
      ],
      [
        'optimize',
        'v. 优化',
        'We optimized the algorithm to run twice as fast.',
        '我们优化了算法，速度提升了一倍。',
      ],
      [
        'idempotent',
        'adj. 幂等的',
        'This API is idempotent, so retries are safe.',
        '这个接口是幂等的，重试是安全的。',
      ],
      [
        'eventual consistency',
        '最终一致性',
        'The system guarantees eventual consistency.',
        '该系统保证最终一致性。',
      ],
      [
        'time complexity',
        '时间复杂度',
        'The time complexity is O(n log n).',
        '时间复杂度是 O(n log n)。',
      ],
      [
        'concurrency',
        'n. 并发',
        'The language has built-in support for concurrency.',
        '这门语言内置支持并发。',
      ],
      [
        'asynchronous',
        'adj. 异步的',
        'We use asynchronous calls to avoid blocking.',
        '我们用异步调用避免阻塞。',
      ],
    ]),
  },
  {
    id: 'en-net',
    lang: 'en',
    title: '网络与安全',
    subtitle: 'English · Network & Security',
    words: en('net', [
      [
        'authentication',
        'n. 认证',
        'We use OAuth for authentication.',
        '我们用 OAuth 做认证。',
      ],
      [
        'authorization',
        'n. 授权',
        'Authorization determines what users can access.',
        '授权决定用户可以访问什么。',
      ],
      [
        'encryption',
        'n. 加密',
        'All data is protected by encryption.',
        '所有数据都有加密保护。',
      ],
      [
        'vulnerability',
        'n. 漏洞',
        'A security vulnerability was discovered in the library.',
        '这个库中发现了一个安全漏洞。',
      ],
      [
        'firewall',
        'n. 防火墙',
        'The firewall blocks unauthorized access.',
        '防火墙阻止未授权的访问。',
      ],
      [
        'protocol',
        'n. 协议',
        'HTTP is a stateless protocol.',
        'HTTP 是无状态协议。',
      ],
      [
        'request / response',
        '请求 / 响应',
        'The server processes the request and sends a response.',
        '服务器处理请求并返回响应。',
      ],
      [
        'timeout',
        'n. 超时',
        'The connection failed due to a timeout.',
        '连接因超时失败了。',
      ],
    ]),
  },
  {
    id: 'en-daily',
    lang: 'en',
    title: '日常生活',
    subtitle: 'English · Daily Life',
    words: en('daily', [
      [
        'appointment',
        'n. 预约',
        'I have a dentist appointment at three.',
        '我三点有牙医预约。',
      ],
      [
        'errand',
        'n. 差事、跑腿',
        'I need to run some errands after work.',
        '下班后我得去办点事。',
      ],
      [
        'commute',
        'n./v. 通勤',
        'My commute takes about forty minutes.',
        '我通勤大约四十分钟。',
      ],
      [
        'grocery',
        'n. 食品杂货',
        'We do grocery shopping on weekends.',
        '我们周末去买菜。',
      ],
      [
        'reservation',
        'n. 预订',
        'I made a reservation for two tonight.',
        '我订了今晚两个人的位子。',
      ],
      [
        'receipt',
        'n. 收据',
        'Could I have the receipt, please?',
        '请给我收据好吗？',
      ],
      ['takeaway', 'n. 外卖', "Let's get takeaway tonight.", '今晚点外卖吧。'],
      [
        'parcel',
        'n. 包裹',
        'Your parcel arrived this morning.',
        '你的包裹今天早上到了。',
      ],
      ['pharmacy', 'n. 药店', 'Is there a pharmacy nearby?', '附近有药店吗？'],
      [
        'landlord',
        'n. 房东',
        'The landlord raised the rent.',
        '房东涨了房租。',
      ],
      [
        'deposit',
        'n. 押金',
        'I paid a one-month deposit.',
        '我付了一个月押金。',
      ],
      [
        'refund',
        'n./v. 退款',
        'They gave me a full refund.',
        '他们给我全额退款了。',
      ],
      [
        'queue',
        'n./v. 排队',
        "There's a long queue at the bank.",
        '银行排着长队。',
      ],
      [
        'directions',
        'n. 路线指引',
        'Could you give me directions to the station?',
        '能告诉我去车站怎么走吗？',
      ],
      [
        'schedule',
        'n. 日程',
        'My schedule is fully booked this week.',
        '我这周日程全满了。',
      ],
    ]),
  },
  {
    id: 'en-smalltalk',
    lang: 'en',
    title: '社交闲聊',
    subtitle: 'English · Small Talk',
    words: en('smalltalk', [
      [
        "How's it going?",
        '最近怎么样？',
        "Hey Mike, how's it going?",
        '嗨 Mike，最近怎么样？',
      ],
      [
        'What are you up to?',
        '在忙什么呢？',
        'What are you up to this weekend?',
        '这周末打算干嘛？',
      ],
      [
        'Long time no see',
        '好久不见',
        'Long time no see! How have you been?',
        '好久不见！过得好吗？',
      ],
      [
        'That sounds like fun',
        '听起来不错',
        'That sounds like fun. Count me in.',
        '听起来不错，算我一个。',
      ],
      [
        'No worries',
        '没关系 / 别担心',
        'No worries, it happens to everyone.',
        '没关系，谁都会遇到。',
      ],
      [
        "I'm just browsing",
        '我随便看看',
        "Thanks, I'm just browsing for now.",
        '谢谢，我先随便看看。',
      ],
      ["It's on me", '我请客', "It's on me today.", '今天我请客。'],
      [
        "Let's grab a coffee",
        '去喝杯咖啡吧',
        "Let's grab a coffee sometime this week.",
        '这周找时间喝杯咖啡吧。',
      ],
      [
        "I can't make it",
        '我去不了了',
        "Sorry, I can't make it tomorrow.",
        '抱歉，明天我去不了了。',
      ],
      [
        'Keep in touch',
        '保持联系',
        'It was great seeing you. Keep in touch!',
        '见到你真高兴，保持联系！',
      ],
      [
        'What do you do?',
        '你做什么工作？',
        'So, what do you do for a living?',
        '你是做什么工作的？',
      ],
      [
        'That makes sense',
        '有道理 / 明白了',
        'Ah, that makes sense now.',
        '啊，这样我就明白了。',
      ],
    ]),
  },
];
